//portfolioValue incl. assets
var portfolioValue = {
  date: "07-10-2021",
  rates: {
    USD_RUB: "72.5682",
    RUB_USD: "0.01378",
    EUR_RUB: "83.9251",
    RUB_EUR: "0.01192",
    EUR_USD: "1.1562",
    USD_EUR: "0.8649",
  },
  total: {
    EUR: "1069.5003",
    USD: "1236.3995",
    RUB: "89724.6663",
  },
  portfolioPercentPerCurrency: {
    EUR: 0,
    USD: 5.988862275213949,
    RUB: 94.01113772478605,
  },
  portfolioPercentPerAssetType: {
    STOCK: 75.09007711358285,
    BOND: 2.268349059836636,
    ETF: 22.641573826580505,
    OTHER: 0,
  },
  assets: [
    {
      ticker: "AGRO",
      account: "Торговый",
      assetType: "STOCK",
      amount: "4",
      price: "1115",
      currency: "EUR",
      valueInEUR: "52.81",
      type: "STOCK:USUAL",
      ffTicker: "AGRO",
      isin: "US7496552057",
      isinQuotes: "US7496552057",
      issuerCountry: {
        code: "US",
        name: {
          en: "United States",
          ru: "Соединенные Штаты",
        },
      },
      sectorCode: "PROCESS.INDUSTRIES",
      sectorNameRU: "Обрабатывающая промышленность",
      sectorNameEN: "Process Industries",
      industryCode: "AGRICULTURAL.COMMODITIES.MILLING",
      industryNameRU: "Сельскохозяйственные продукты и помол зерна",
      industryNameEN: "Agricultural Commodities Milling",
      equalInRUB: 4460,
      equalInEUR: "53.1632",
      equalInUSD: "61.4588",
      portfolioPercent: 4.970844795461956,
      kind: "STOCK",
    },
    {
      ticker: "ALRS",
      account: "Торговый",
      assetType: "STOCK",
      amount: "10",
      price: "138.01",
      currency: "RUB",
      valueInEUR: "16.34",
      type: "STOCK:USUAL",
      ffTicker: "ALRS",
      isin: "RU0007252813",
      isinQuotes: "RU0007252813",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "NON.ENERGY.MINERALS",
      sectorNameRU: "Несырьевые полезные ископаемые",
      sectorNameEN: "Non Energy Minerals",
      industryCode: "OTHER.METALS.MINERALS",
      industryNameRU: "Прочие металлы и минералы",
      industryNameEN: "Other Metals Minerals",
      equalInRUB: 1380.1,
      equalInEUR: "16.4508",
      equalInUSD: "19.0178",
      portfolioPercent: 1.5381762866265678,
      kind: "STOCK",
    },
    {
      ticker: "CHMF",
      account: "Торговый",
      assetType: "STOCK",
      amount: "6",
      price: "1504.8",
      currency: "RUB",
      valueInEUR: "106.9",
      type: "STOCK:USUAL",
      ffTicker: "CHMF",
      isin: "RU0009046510",
      isinQuotes: "RU0009046510",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "NON.ENERGY.MINERALS",
      sectorNameRU: "Несырьевые полезные ископаемые",
      sectorNameEN: "Non Energy Minerals",
      industryCode: "STEEL",
      industryNameRU: "Сталь",
      industryNameEN: "Steel",
      equalInRUB: 9028.8,
      equalInEUR: "107.6233",
      equalInUSD: "124.4169",
      portfolioPercent: 10.06295182899902,
      kind: "STOCK",
    },
    {
      ticker: "ETLN",
      account: "Торговый",
      assetType: "STOCK",
      amount: "5",
      price: "112.7",
      currency: "RUB",
      valueInEUR: "6.67",
      type: "STOCK:USUAL",
      ffTicker: "ETLN",
      isin: "US29760G1031",
      isinQuotes: "US29760G1031",
      issuerCountry: {
        code: "US",
        name: {
          en: "United States",
          ru: "Соединенные Штаты",
        },
      },
      sectorCode: "CONSUMER.DURABLES",
      sectorNameRU: "Потребительские товары длительного пользования",
      sectorNameEN: "Consumer Durables",
      industryCode: "HOMEBUILDING",
      industryNameRU: "Строительство жилья",
      industryNameEN: "Homebuilding",
      equalInRUB: 563.5,
      equalInEUR: "6.7169",
      equalInUSD: "7.7650",
      portfolioPercent: 0.6280409645513891,
      kind: "STOCK",
    },
    {
      ticker: "FIPO",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1",
      price: "33.01",
      currency: "USD",
      valueInEUR: "28.5",
      type: "STOCK:ETF",
      ffTicker: "FIPO.SPB",
      isin: "RU000A101NK4",
      isinQuotes: "RU000A101NK4",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      equalInUSD: 33.01,
      equalInEUR: "28.5503",
      equalInRUB: "2395.4763",
      portfolioPercent: 2.669499017438331,
      kind: "ETF",
    },
    {
      ticker: "FXCN",
      account: "Торговый",
      assetType: "STOCK",
      amount: "3",
      price: "3067",
      currency: "RUB",
      valueInEUR: "108.94",
      type: "STOCK:ETF",
      ffTicker: "FXCN",
      isin: "IE00BD3QFB18",
      isinQuotes: "IE00BD3QFB18",
      issuerCountry: {
        code: "IE",
        name: {
          en: "Ireland",
          ru: "Ирландия",
        },
      },
      sectorCode: "MISCELLANEOUS",
      sectorNameRU: "Разное",
      sectorNameEN: "Miscellaneous",
      industryCode: "INVESTMENT.TRUSTS.MUTUAL.FUNDS",
      industryNameRU: "Инвестиционные компании и паевые фонды",
      industryNameEN: "Investment Trusts Mutual Funds",
      equalInRUB: 9201,
      equalInEUR: "109.6759",
      equalInUSD: "126.7898",
      portfolioPercent: 10.254873233789649,
      kind: "ETF",
    },
    {
      ticker: "FXES",
      account: "Торговый",
      assetType: "STOCK",
      amount: "65",
      price: "66.85",
      currency: "RUB",
      valueInEUR: "51.45",
      type: "STOCK:ETF",
      ffTicker: "FXES",
      isin: "IE00BNYK7W79",
      isinQuotes: "IE00BNYK7W79",
      issuerCountry: {
        code: "IE",
        name: {
          en: "Ireland",
          ru: "Ирландия",
        },
      },
      equalInRUB: 4345.25,
      equalInEUR: "51.7954",
      equalInUSD: "59.8775",
      portfolioPercent: 4.842953293234233,
      kind: "ETF",
    },
    {
      ticker: "FXIM",
      account: "Торговый",
      assetType: "STOCK",
      amount: "15",
      price: "92.67",
      currency: "RUB",
      valueInEUR: "16.46",
      type: "STOCK:ETF",
      ffTicker: "FXIM",
      isin: "IE00BNC2D728",
      isinQuotes: "IE00BNC2D728",
      issuerCountry: {
        code: "IE",
        name: {
          en: "Ireland",
          ru: "Ирландия",
        },
      },
      sectorCode: "MISCELLANEOUS",
      sectorNameRU: "Разное",
      sectorNameEN: "Miscellaneous",
      industryCode: "INVESTMENT.TRUSTS.MUTUAL.FUNDS",
      industryNameRU: "Инвестиционные компании и паевые фонды",
      industryNameEN: "Investment Trusts Mutual Funds",
      equalInRUB: 1390.05,
      equalInEUR: "16.5694",
      equalInUSD: "19.1549",
      portfolioPercent: 1.5492655775786135,
      kind: "ETF",
    },
    {
      ticker: "FXWO",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1100",
      price: "1.8014",
      currency: "RUB",
      valueInEUR: "23.46",
      type: "STOCK:ETF",
      ffTicker: "FXWO",
      isin: "IE00BK224L29",
      isinQuotes: "IE00BK224L29",
      issuerCountry: {
        code: "IE",
        name: {
          en: "Ireland",
          ru: "Ирландия",
        },
      },
      sectorCode: "MISCELLANEOUS",
      sectorNameRU: "Разное",
      sectorNameEN: "Miscellaneous",
      industryCode: "INVESTMENT.TRUSTS.MUTUAL.FUNDS",
      industryNameRU: "Инвестиционные компании и паевые фонды",
      industryNameEN: "Investment Trusts Mutual Funds",
      equalInRUB: 1981.54,
      equalInEUR: "23.6200",
      equalInUSD: "27.3056",
      portfolioPercent: 2.2085080294040127,
      kind: "ETF",
    },
    {
      ticker: "GAZP",
      account: "Торговый",
      assetType: "STOCK",
      amount: "10",
      price: "363.25",
      currency: "RUB",
      valueInEUR: "43.01",
      type: "STOCK:USUAL",
      ffTicker: "GAZP",
      isin: "RU0007661625",
      isinQuotes: "RU0007661625",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "ENERGY.MINERALS",
      sectorNameRU: "Энергетические и минеральные ресурсы",
      sectorNameEN: "Energy Minerals",
      industryCode: "INTEGRATED.OIL",
      industryNameRU: "Интегрированная нефтяная промышленность",
      industryNameEN: "Integrated Oil",
      equalInRUB: 3632.5,
      equalInEUR: "43.2994",
      equalInUSD: "50.0558",
      portfolioPercent: 4.048563614241155,
      kind: "STOCK",
    },
    {
      ticker: "LSRG",
      account: "Торговый",
      assetType: "STOCK",
      amount: "2",
      price: "762.4",
      currency: "RUB",
      valueInEUR: "18.05",
      type: "STOCK:USUAL",
      ffTicker: "LSRG",
      isin: "RU000A0JPFP0",
      isinQuotes: "RU000A0JPFP0",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "FINANCE",
      sectorNameRU: "Финансы",
      sectorNameEN: "Finance",
      industryCode: "REAL.ESTATE.DEVELOPMENT",
      industryNameRU: "Девелопмент недвижимости",
      industryNameEN: "Real Estate Development",
      equalInRUB: 1524.8,
      equalInEUR: "18.1756",
      equalInUSD: "21.0117",
      portfolioPercent: 1.6994478636424881,
      kind: "STOCK",
    },
    {
      ticker: "MOEX",
      account: "Торговый",
      assetType: "STOCK",
      amount: "10",
      price: "170.96",
      currency: "RUB",
      valueInEUR: "20.24",
      type: "STOCK:USUAL",
      ffTicker: "MOEX",
      isin: "RU000A0JR4A1",
      isinQuotes: "RU000A0JR4A1",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "FINANCE",
      sectorNameRU: "Финансы",
      sectorNameEN: "Finance",
      industryCode: "INVESTMENT.BANKS.BROKERS",
      industryNameRU: "Инвестиционные банки, брокеры",
      industryNameEN: "Investment Banks Brokers",
      equalInRUB: 1709.6000000000001,
      equalInEUR: "20.3784",
      equalInUSD: "23.5583",
      portfolioPercent: 1.905413210262774,
      kind: "STOCK",
    },
    {
      ticker: "NKNCP",
      account: "Торговый",
      assetType: "STOCK",
      amount: "10",
      price: "101.4",
      currency: "RUB",
      valueInEUR: "12.01",
      type: "STOCK:PRIVILEGED",
      ffTicker: "NKNCP",
      isin: "RU0006765096",
      isinQuotes: "RU0006765096",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "PROCESS.INDUSTRIES",
      sectorNameRU: "Обрабатывающая промышленность",
      sectorNameEN: "Process Industries",
      industryCode: "CHEMICALS.SPECIALTY",
      industryNameRU: "Химическая промышленность: специализированные химикаты",
      industryNameEN: "Chemicals Specialty",
      equalInRUB: 1014,
      equalInEUR: "12.0869",
      equalInUSD: "13.9729",
      portfolioPercent: 1.130144610525121,
      kind: "STOCK",
    },
    {
      ticker: "NLMK",
      account: "Торговый",
      assetType: "STOCK",
      amount: "50",
      price: "212.5",
      currency: "RUB",
      valueInEUR: "125.8",
      type: "STOCK:USUAL",
      ffTicker: "NLMK",
      isin: "RU0009046452",
      isinQuotes: "RU0009046452",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "NON.ENERGY.MINERALS",
      sectorNameRU: "Несырьевые полезные ископаемые",
      sectorNameEN: "Non Energy Minerals",
      industryCode: "STEEL",
      industryNameRU: "Сталь",
      industryNameEN: "Steel",
      equalInRUB: 10625,
      equalInEUR: "126.6500",
      equalInUSD: "146.4125",
      portfolioPercent: 11.841978912955893,
      kind: "STOCK",
    },
    {
      ticker: "NMTP",
      account: "Торговый",
      assetType: "STOCK",
      amount: "200",
      price: "7.84",
      currency: "RUB",
      valueInEUR: "18.57",
      type: "STOCK:USUAL",
      ffTicker: "NMTP",
      isin: "RU0009084446",
      isinQuotes: "RU0009084446",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "TRANSPORTATION",
      sectorNameRU: "Транспорт",
      sectorNameEN: "Transportation",
      industryCode: "OTHER.TRANSPORTATION",
      industryNameRU: "Прочие виды транспорта",
      industryNameEN: "Other Transportation",
      equalInRUB: 1568,
      equalInEUR: "18.6906",
      equalInUSD: "21.6070",
      portfolioPercent: 1.7476011928187398,
      kind: "STOCK",
    },
    {
      ticker: "NVTK",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1",
      price: "1931.8",
      currency: "RUB",
      valueInEUR: "22.87",
      type: "STOCK:USUAL",
      ffTicker: "NVTK",
      isin: "RU000A0DKVS5",
      isinQuotes: "RU000A0DKVS5",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "ENERGY.MINERALS",
      sectorNameRU: "Энергетические и минеральные ресурсы",
      sectorNameEN: "Energy Minerals",
      industryCode: "INTEGRATED.OIL",
      industryNameRU: "Интегрированная нефтяная промышленность",
      industryNameEN: "Integrated Oil",
      equalInRUB: 1931.8,
      equalInEUR: "23.0271",
      equalInUSD: "26.6202",
      portfolioPercent: 2.15307092480479,
      kind: "STOCK",
    },
    {
      ticker: "PIKK",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1",
      price: "1278",
      currency: "RUB",
      valueInEUR: "15.13",
      type: "STOCK:USUAL",
      ffTicker: "PIKK",
      isin: "RU000A0JP7J7",
      isinQuotes: "RU000A0JP7J7",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "CONSUMER.DURABLES",
      sectorNameRU: "Потребительские товары длительного пользования",
      sectorNameEN: "Consumer Durables",
      industryCode: "HOMEBUILDING",
      industryNameRU: "Строительство жилья",
      industryNameEN: "Homebuilding",
      equalInRUB: 1278,
      equalInEUR: "15.2338",
      equalInUSD: "17.6108",
      portfolioPercent: 1.424384827194532,
      kind: "STOCK",
    },
    {
      ticker: "POLY",
      account: "Торговый",
      assetType: "STOCK",
      amount: "6",
      price: "1218.1",
      currency: "RUB",
      valueInEUR: "86.54",
      type: "STOCK:USUAL",
      ffTicker: "POLY",
      isin: "JE00B6T5S470",
      isinQuotes: "JE00B6T5S470",
      issuerCountry: {
        code: "JE",
        name: {
          en: "Jersey",
          ru: "Джерси",
        },
      },
      sectorCode: "NON.ENERGY.MINERALS",
      sectorNameRU: "Несырьевые полезные ископаемые",
      sectorNameEN: "Non Energy Minerals",
      industryCode: "PRECIOUS.METALS",
      industryNameRU: "Драгоценные металлы",
      industryNameEN: "Precious Metals",
      equalInRUB: 7308.599999999999,
      equalInEUR: "87.1185",
      equalInUSD: "100.7125",
      portfolioPercent: 8.145720015225802,
      kind: "STOCK",
    },
    {
      ticker: "RTKM",
      account: "Торговый",
      assetType: "STOCK",
      amount: "20",
      price: "89.99",
      currency: "RUB",
      valueInEUR: "21.31",
      type: "STOCK:USUAL",
      ffTicker: "RTKM",
      isin: "RU0008943394",
      isinQuotes: "RU0008943394",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "COMMUNICATIONS",
      sectorNameRU: "Связь",
      sectorNameEN: "Communications",
      industryCode: "SPECIALTY.TELECOMMUNICATIONS",
      industryNameRU: "Специализированные телекоммуникации",
      industryNameEN: "Specialty Telecommunications",
      equalInRUB: 1799.8,
      equalInEUR: "21.4536",
      equalInUSD: "24.8012",
      portfolioPercent: 2.005946141389582,
      kind: "STOCK",
    },
    {
      ticker: "RU000A100L63",
      account: "Торговый",
      assetType: "BOND",
      amount: "1",
      price: "102.48",
      currency: "RUB",
      valueInEUR: "12.14",
      type: "BOND:USUAL",
      ffTicker: "RU000A100L63",
      isin: "RU000A100L63",
      isinQuotes: "RU000A100L63",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      equalInEUR: "12.1400",
      equalInUSD: "14.0363",
      equalInRUB: "1018.8507",
      portfolioPercent: 1.1351095460188279,
      kind: "BOND",
    },
    {
      ticker: "RU000A103DT2",
      account: "Торговый",
      assetType: "BOND",
      amount: "1",
      price: "101.82",
      currency: "RUB",
      valueInEUR: "12.12",
      type: "BOND:USUAL",
      ffTicker: "RU000A103DT2",
      isin: "RU000A103DT2",
      isinQuotes: "RU000A103DT2",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      equalInEUR: "12.1200",
      equalInUSD: "14.0131",
      equalInRUB: "1017.1722",
      portfolioPercent: 1.1332395138178082,
      kind: "BOND",
    },
    {
      ticker: "SBER",
      account: "Торговый",
      assetType: "STOCK",
      amount: "20",
      price: "338.48",
      currency: "RUB",
      valueInEUR: "80.15",
      type: "STOCK:USUAL",
      ffTicker: "SBER",
      isin: "RU0009029540",
      isinQuotes: "RU0009029540",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "FINANCE",
      sectorNameRU: "Финансы",
      sectorNameEN: "Finance",
      industryCode: "REGIONAL.BANKS",
      industryNameRU: "Региональные банки",
      industryNameEN: "Regional Banks",
      equalInRUB: 6769.6,
      equalInEUR: "80.6936",
      equalInUSD: "93.2851",
      portfolioPercent: 7.544981520809299,
      kind: "STOCK",
    },
    {
      ticker: "SNGSP",
      account: "Торговый",
      assetType: "STOCK",
      amount: "100",
      price: "39.72",
      currency: "RUB",
      valueInEUR: "47.03",
      type: "STOCK:PRIVILEGED",
      ffTicker: "SNGSP",
      isin: "RU0009029524",
      isinQuotes: "RU0009029524",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "ENERGY.MINERALS",
      sectorNameRU: "Энергетические и минеральные ресурсы",
      sectorNameEN: "Energy Minerals",
      industryCode: "INTEGRATED.OIL",
      industryNameRU: "Интегрированная нефтяная промышленность",
      industryNameEN: "Integrated Oil",
      equalInRUB: 3972,
      equalInEUR: "47.3462",
      equalInUSD: "54.7342",
      portfolioPercent: 4.426945929795439,
      kind: "STOCK",
    },
    {
      ticker: "RU000A103N35",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1",
      price: "13.8059",
      currency: "USD",
      valueInEUR: "11.92",
      type: "STOCK:ETF",
      ffTicker: "SPBX_USD.FUNDS",
      isin: "RU000A103N35",
      isinQuotes: "RU000A103N35",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      equalInUSD: 13.8059,
      equalInEUR: "11.9407",
      equalInRUB: "1001.8693",
      portfolioPercent: 1.1164746751356684,
      kind: "ETF",
    },
    {
      ticker: "T",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1",
      price: "27.24",
      currency: "USD",
      valueInEUR: "23.52",
      type: "STOCK:USUAL",
      ffTicker: "T.SPB",
      isin: "US00206R1023",
      isinQuotes: "US00206R1023",
      issuerCountry: {
        code: "US",
        name: {
          en: "United States",
          ru: "Соединенные Штаты",
        },
      },
      sectorCode: "COMMUNICATIONS",
      sectorNameRU: "Связь",
      sectorNameEN: "Communications",
      industryCode: "MAJOR.TELECOMMUNICATIONS",
      industryNameRU: "Ведущие телекоммуникационные компании",
      industryNameEN:
        "Https:/ru.tradingview.com/markets/stocks Usa/sectorandindustry Industry/major Telecommunications/",
      equalInUSD: 27.24,
      equalInEUR: "23.5599",
      equalInRUB: "1976.7578",
      portfolioPercent: 2.202888582639949,
      kind: "STOCK",
    },
    {
      ticker: "TATN",
      account: "Торговый",
      assetType: "STOCK",
      amount: "2",
      price: "532.1",
      currency: "RUB",
      valueInEUR: "12.6",
      type: "STOCK:USUAL",
      ffTicker: "TATN",
      isin: "RU0009033591",
      isinQuotes: "RU0009033591",
      issuerCountry: {
        code: "RU",
        name: {
          en: "Russia",
          ru: "Россия",
        },
      },
      sectorCode: "ENERGY.MINERALS",
      sectorNameRU: "Энергетические и минеральные ресурсы",
      sectorNameEN: "Energy Minerals",
      industryCode: "OIL.GAS.PRODUCTION",
      industryNameRU: "Нефтегазовое производство",
      industryNameEN: "Oil Gas Production",
      equalInRUB: 1064.2,
      equalInEUR: "12.6853",
      equalInUSD: "14.6647",
      portfolioPercent: 1.186095973979624,
      kind: "STOCK",
    },
    {
      ticker: "YNDX",
      account: "Торговый",
      assetType: "STOCK",
      amount: "1",
      price: "5766.4",
      currency: "RUB",
      valueInEUR: "68.28",
      type: "STOCK:USUAL",
      ffTicker: "YNDX",
      isin: "NL0009805522",
      isinQuotes: "NL0009805522",
      issuerCountry: {
        code: "NL",
        name: {
          en: "Netherlands",
          ru: "Нидерланды",
        },
      },
      sectorCode: "TECHNOLOGY.SERVICES",
      sectorNameRU: "Технологии",
      sectorNameEN: "Technology Services",
      industryCode: "INTERNET.SOFTWARE.SERVICES",
      industryNameRU: "Программное обеспечение для интернета",
      industryNameEN: "Internet Software Services",
      equalInRUB: 5766.4,
      equalInEUR: "68.7355",
      equalInUSD: "79.4610",
      portfolioPercent: 6.426879917658742,
      kind: "STOCK",
    },
  ],
};
